name: Daily README Update

on:
  schedule:
    - cron: '0 2/3 * * *'
  workflow_dispatch: # Allows you to trigger it manually from the Actions tab

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Update Bash Script
      run: bash ./update_readme2.sh
